Initial Commit
tsundokuapp/tsundoku pull request #23
Opened 2024-10-12 02:57 UTC by Ganim

## Descreva as mudanças feitas nessa PR:

## Ela resolve alguma issue? Informe o número: 

## Preencha o checklist antes de enviar a PR (delete o que não usar):
- [ ] Bug fix (conserta bugs e não causam modificações em outros componentes).
- [ ] New feature (adiciona nova funcionalidade).
- [ ] Breaking change (Esta PR pode causar erros em outros componentes).
- [ ] É preciso atualizar a documentação.
- [ ] Esta PR possui teste inclusos.

## Screenshots (se necessário):

2024-10-12 14:41 UTC, NaySoares requested changes
As configs não podem ser deletadas do projeto pastas iniciadas com "." (ponto)

2024-10-12 16:15 UTC, NaySoares requested changes
PNPM não está resolvendo os pacotes e dispara erro de não reconhecer o pnpm-lock.yarn, porém outros gerenciadores conseguem resolver sem avisos.

2024-10-12 16:15 UTC, NaySoares commented on .eslintignore
Tem certeza que não precisamos desse arquivo?

2024-10-12 16:15 UTC, NaySoares commented on .eslintrc.json
> +    "import/order": [
essa regra não é reconhecida dentro de "settings", ao levar de volta pra "rules" volta a funcionar, verificar se não existe algum plugin instalado na maquina resolvendo as diferença de rules e settings

2024-10-12 16:15 UTC, NaySoares commented on src/app/layout.tsx
> +  title: 'Create Next App',
alterar o title, description e "lang="en" na linha 27

2024-10-12 16:15 UTC, NaySoares commented on tsconfig.json
> +    "moduleResolution": "bundler",
essa config está ok agora porém precisamos ficar atentos quando os testes forem implementados, pois pode ser preciso adaptar o Jest

2024-10-12 16:31 UTC, Ganim commented on src/app/layout.tsx
> +  title: 'Create Next App',
Já foi feito em outro commit que ainda não subi

2024-10-12 16:35 UTC, Ganim commented on tsconfig.json
> +    "moduleResolution": "bundler",
Certo

2024-10-12 16:36 UTC, Ganim commented on .eslintignore
Vou adicionando os arquivos a medida que vou precisando.. como ainda não foi o caso, ele não está na estruturam, mas pode chegar a ser adicionado.

2024-10-12 16:36 UTC, Ganim commented on .eslintrc.json
> +    "import/order": [
Fui tentar resolver e bugou o lint aqui kkkkk vou ver isso mais a fundo

2024-10-12 19:54 UTC, Ganim commented on .eslintrc.json
> +    "import/order": [
De fato aqui só funciona do jeito que fiz o primeiro commit... todas as vezes que mudei quebrou.

2024-10-12 20:46 UTC, NaySoares commented on src/app/(webapp)/layout.tsx
> +import type { ReactNode } from 'react';
Erro de importação, o caminho diferente do real: "components" != "Components"

A importação do ReactNode deve ficar na parte superior.
Se ainda não tiver, instale as extenções do eslint e prettier no vscode e adicione a config abaixo no settings.json

"editor.defaultFormatter": "vscode.typescript-language-features",
"editor.formatOnSave": true,
"editor.codeActionsOnSave": {
  "source.fixAll": "explicit",
   "source.fixAll.eslint": "explicit"
},

2024-10-12 20:47 UTC, NaySoares commented on src/app/(webapp)/layout.tsx
> +export default function webaapLayout({ children }: { children: ReactNode }) {
Erro de escrita

2024-10-12 21:01 UTC, NaySoares requested changes
- Renomear os arquivos para seguir a convenção de nomenclatura, componentes devem ser escritos com PascalCase tanto na sua declaração quanto no nome do arquivo.
- Padronizar a nomenclatura das pastas que não atingem o comportamento do Next, ora está iniciando com maiúsculo, ora com minúsculo.
- Deletar pastas vazias e arquivos não usados
- Adicionar os testes dos componentes

2024-10-12 21:01 UTC, NaySoares commented on src/components/footer/footer.tsx
> +    <div className="flex items-center justify-between bg-gray-300 h-[120px] px-[180px]">
Usar footer invés de div

2024-10-12 21:01 UTC, NaySoares commented on src/components/header/header.tsx
> +    <div className="flex items-center justify-between bg-slate-900 h-[120px] px-[180px]">
Usar header invés de div

2024-10-13 01:06 UTC, Ganim commented on src/components/header/header.tsx
> +    <div className="flex items-center justify-between bg-slate-900 h-[120px] px-[180px]">
Feito

2024-10-13 01:06 UTC, Ganim commented on src/components/footer/footer.tsx
> +    <div className="flex items-center justify-between bg-gray-300 h-[120px] px-[180px]">
Feito

2024-10-13 01:13 UTC, Ganim commented on src/components/header/header.tsx
> +    <div className="flex items-center justify-between bg-slate-900 h-[120px] px-[180px]">
> Renomear os arquivos para seguir a convenção de nomenclatura, componentes devem ser escritos com PascalCase tanto na sua declaração quanto no nome do arquivo.

- Então,  essa semana eu estava numa discussão sobre este tema com o pessoal da Rocket, e essa conversão de componentes usar PascalCase dentro do Next está cada vez mais em baixa... O motivo é que todos os arquivos do Next devem ser escritos em minúsculo, e apenas os componentes estavam ficando com PascalCase... o que não faz muito sentido dentro do projeto. Então estão deixando de usar, e particularmente eu também prefiro manter o padrão em todo o projeto.

> Padronizar a nomenclatura das pastas que não atingem o comportamento do Next, ora está iniciando com maiúsculo, ora com minúsculo.

- Todas as pastas e arquivos estão com letra minuscula... não achei isso no projeto.

> Deletar pastas vazias e arquivos não usados

- Também não achei pastas vazias

> Adicionar os testes dos componentes

- Calma jovem, logo logo virá

2024-10-13 15:42 UTC, merged