Create Reader App
tsundokuapp/tsundoku pull request #31
Opened 2024-11-18 02:31 UTC by Ganim

## Descreva as mudanças feitas nessa PR:
Essa PR tem por objetivo adicionar a aplicação de leitura (Reader App) ao site. 
Todos os commits realizados são pertinentes a estruturação dessa aplicação e o funcionamento da leitura de Comics.
A leitura de Novels será adiciona posteriormente,
A nova funcionalidade pode ser acessada ao clicar na leitura de um capitulo dentro do proprio projeto ou pelo link:
http://localhost:3000/reader/comics/kage-no-jitsuryokusha-ni-naritakute/24
Como exemplo. 

- [x] New feature (adiciona nova funcionalidade).
- [x] Breaking change (Esta PR pode causar erros em outros componentes).

2024-11-24 20:35 UTC, NaySoares requested changes
Antes de fazer do CR vamos para um SR, temos alguns pontos:
1 - Ao clicar no dropdown dentro do leitor o texto altera para o último item da lista, por exemplo, caso o cap tenha 30 páginas e está na 4 página (mostrando no dropdown) ao clicar ele mostra "Página 30", deve ser mantida a página atual nesse dropdown e mudar apenas se clicar em outra página. (ocorre em todos os dropdowns)
2 - Se estiver em página simples e em um número par, por exemplo na página 2, e mudar para página dupla o leitor numera assim: 2-3, 4-5... e com isso não se pode mais acessar a página 1 sem sair do modo "Página dupla"
3 - Está faltando responsividade na tela do leitor, nesse caso não vamos deixar para adicionar posteriormente, o leitor precisa já está minimamente responsivo.

2025-01-10 20:46 UTC, NaySoares requested changes
Além dos citados, a página deve conter responsividade mínima, e considerando a complexidade que o leitor pode alcançar precisamos de testes unitarios em seus componentes

2025-01-10 20:46 UTC, NaySoares commented on package.json
> +    "tailwind-scrollbar": "^3.1.0",
Se possível, implementar o conteúdo dessa lib diretamente no sistema

2025-01-10 20:46 UTC, NaySoares commented on src/@types/ChapterListItem.d.ts
> +}
Mover as interfaces para a pasta types

2025-01-10 20:46 UTC, NaySoares commented on src/app/reader/comics/[slug]/[chapter]/page.tsx
> +import type { ScrollMode } from '@/@types/ScrollMode';
criar um index na pasta de exportação desses componentes para diminuir a quantidade de linhas no import

2025-01-10 20:46 UTC, NaySoares commented on src/app/reader/comics/[slug]/[chapter]/page.tsx
> +  // Fix double scroll mode when currentPage is even
Comentários em português

2025-01-10 20:46 UTC, NaySoares commented on src/app/reader/novels/[slug]/[volume]/[chapter]/page.tsx
> +// interface NovelReaderProps {
remover se não é necessário

2025-01-10 20:46 UTC, NaySoares commented on src/app/reader/novels/[slug]/[volume]/[chapter]/page.tsx
> +      /> */}
remover se não for necessário

2025-01-10 20:46 UTC, NaySoares commented on src/components/common/dropdown/DropdownBreakLine.tsx
> +import { twMerge } from 'tailwind-merge';
Trocar pelo cn

2025-01-10 20:46 UTC, NaySoares commented on src/components/common/dropdown/DropdownText.tsx
> +import { twMerge } from 'tailwind-merge';
Trocar pelo CN

2025-01-10 20:46 UTC, NaySoares commented on src/components/project/Chapter.tsx
>        className={twMerge(
trocar pelo cn

2025-01-10 20:46 UTC, NaySoares commented on src/components/reader/ActionsBarContainer.tsx
> +      <div className="flex flex-row gap-2">
adicionar responsividade

2025-01-10 20:46 UTC, NaySoares commented on src/components/reader/ReaderContainer.tsx
> +import { twMerge } from 'tailwind-merge';
trocar pelo cn

2025-01-10 20:46 UTC, NaySoares commented on src/components/reader/ReaderContainer.tsx
> +      className={(twMerge('flex items-center justify-center'), className)}
trocar pelo cn

2025-01-10 20:46 UTC, NaySoares commented on src/app/reader/comics/[slug]/[chapter]/page.tsx
> +    champter: string;
renomear variavel

2025-01-10 20:46 UTC, NaySoares commented on src/components/reader/actions/ActionChapterListWithVolume.tsx
> +                router.push(ItemUrl);
não é necessário validar esse itemUrl?

2025-01-10 20:46 UTC, NaySoares commented on src/components/reader/actions/ActionScrollModeList.tsx
> +    onScrollModeChange?.(scrollMode);
porque scrollMode é alterado com dois states? aqui e pela função setScrollMode

2025-01-10 20:46 UTC, NaySoares commented on src/components/reader/comic/ComicDoubleView.tsx
> +import { twMerge } from 'tailwind-merge';
trocar pra cn

2025-01-10 20:46 UTC, NaySoares commented on src/components/reader/comic/ComicInfiniteView.tsx
> +import { twMerge } from 'tailwind-merge';
trocar pra cn

2025-01-10 20:46 UTC, NaySoares commented on src/components/reader/utils/PageSlider/PageSliderContainer.tsx
> +    }
reavaliar essa logica, acredito que um if seja suficiente para o handlePreviousPage e outro para o handleNextPage, além disso apenas uma variavel pode substituir as previousPage e nextPage, idealmente alocar elas dentro da função onde ela é usada e não externamente.

assuma uma pagina alvo para a nova variavel e manipule a logica de pagina anterior e próxima seguindo essa pagina alvo.

2025-01-10 20:46 UTC, NaySoares commented on src/components/reader/utils/PageSlider/PageSliderLeft.tsx
> +import { twMerge } from 'tailwind-merge';
trocar para cn

2025-01-10 20:46 UTC, NaySoares commented on src/components/reader/utils/PageSlider/PageSliderRight.tsx
> +import { twMerge } from 'tailwind-merge';
trocar para cn

2025-01-10 20:46 UTC, NaySoares commented on src/components/reader/actions/ActionScrollModeList.tsx
> +
salvar a opção escolhida no localStorage

2025-01-10 20:46 UTC, NaySoares commented on src/components/reader/utils/ProgressBar.tsx
> +export function ProgressBar({
Renomear para algo especifico do reader, adicionar um sufixo talvez.

2025-01-10 20:46 UTC, NaySoares commented on src/fakeApi/comicChapter.tsx
> +    '/comic-example/3.jpg',
remover metade dessas importações, precisamos de no maximo 5 imagens para testar o leitor

2025-01-10 20:46 UTC, NaySoares commented on src/helpers/pageList/CheckPageRange.tsx
> +    throw new Error('Page number cannot be lower than zero.');
trocar para português

2025-01-10 20:46 UTC, NaySoares commented on src/helpers/pageList/CheckPageRange.tsx
> +    throw new Error('Page number cannot be highter than total pages.');
Trocar para português

2025-01-10 20:46 UTC, NaySoares commented on tailwind.config.ts
> +  plugins: [require('tailwind-scrollbar')],
remover se for implementado no sistema

2025-02-19 01:58 UTC, Ganim commented on src/app/reader/comics/[slug]/[chapter]/page.tsx
> +import type { ScrollMode } from '@/@types/ScrollMode';
Nào entendi... quais componentes?

2025-02-19 04:36 UTC, NaySoares requested changes
- Separar em PR diferentes para cada tópico.
- Adicionar testes minimos.
- A tela inicial está com responsividade quebrada, index de novels não tem uma boa responsividade para mobile, as letras correm para fora ta tela
- Já existindo um componente Accordion no projeto, existe necessidade de mais um?
- para os testes de snapshot use o comando "jest --updateSnapshot" ou adicione a flag no fim dos testes "-- -u", porém avalie se é realmente necessário uma alteração de snapshot antes de fazer

2025-02-23 12:38 UTC, merged